2025-04-15 14:14:38,874 INFO    MainThread:15062 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-04-15 14:14:38,874 INFO    MainThread:15062 [wandb_setup.py:_flush():67] Configure stats pid to 15062
2025-04-15 14:14:38,874 INFO    MainThread:15062 [wandb_setup.py:_flush():67] Loading settings from /home/klrshak/.config/wandb/settings
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_setup.py:_flush():67] Loading settings from /home/klrshak/work/VisionLang/whereami-text2sgm/playground/graph_models/models/wandb/settings
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/klrshak/work/VisionLang/whereami-text2sgm/playground/graph_models/models/wandb/run-20250415_141438-9is3acmg/logs/debug.log
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/klrshak/work/VisionLang/whereami-text2sgm/playground/graph_models/models/wandb/run-20250415_141438-9is3acmg/logs/debug-internal.log
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:init():761] calling init triggers
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'architecture': 'self attention cross attention', 'dataset': 'ScanScribe_cleaned', 'mode': 'online', 'epoch': 100, 'lr': 0.0001, 'weight_decay': 5e-05, 'N': 1, 'overlap_thr': 0.8, 'cos_sim_thr': 0.5, 'batch_size': 32, 'training_set_size': 2847, 'test_set_size': 712, 'graph_size_min': 4, 'contrastive_loss': True, 'valid_top_k': [1, 2, 3, 5], 'use_attributes': True, 'training_with_cross_val': True, 'folds': 10, 'skip_k_fold': True, 'entire_training_set': False, 'subgraph_ablation': True, 'eval_iters': 30, 'eval_iter_count': 10, 'out_of': 10, 'model_name': 'model_NO_subg_100_epochs_30_eval_iters_loss_ablation_m_cut_cross', 'loss_ablation_m': True, 'loss_ablation_c': False, 'eval_only_c': False, 'continue_training': 0, 'continue_training_model': None, 'eval_entire_dataset': False, 'heads': 2, 'scannet': False, 'scanscribe_auto_gen': False, '_wandb': {}}
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:init():784] starting backend
2025-04-15 14:14:38,875 INFO    MainThread:15062 [wandb_init.py:init():788] sending inform_init request
2025-04-15 14:14:38,880 INFO    MainThread:15062 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-15 14:14:38,880 INFO    MainThread:15062 [wandb_init.py:init():798] backend started and connected
2025-04-15 14:14:38,883 INFO    MainThread:15062 [wandb_init.py:init():891] updated telemetry
2025-04-15 14:14:38,891 INFO    MainThread:15062 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-04-15 14:14:39,486 INFO    MainThread:15062 [wandb_init.py:init():990] starting run threads in backend
2025-04-15 14:14:39,689 INFO    MainThread:15062 [wandb_run.py:_console_start():2375] atexit reg
2025-04-15 14:14:39,689 INFO    MainThread:15062 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-04-15 14:14:39,689 INFO    MainThread:15062 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-04-15 14:14:39,689 INFO    MainThread:15062 [wandb_run.py:_redirect():2315] Redirects installed.
2025-04-15 14:14:39,691 INFO    MainThread:15062 [wandb_init.py:init():1032] run started, returning control to user process
2025-04-15 16:56:17,957 INFO    MsgRouterThr:15062 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-04-15 16:56:18,394 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,399 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,400 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,400 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,401 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,401 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,402 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,402 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,403 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,403 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,404 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,404 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,405 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,406 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,406 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,407 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,407 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,408 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,408 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,409 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,409 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,410 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,410 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,411 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,411 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,412 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,412 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,413 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,413 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,413 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,413 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-15 16:56:18,414 ERROR   MainThread:15062 [redirect.py:_on_write():661] error in stderr callback
Traceback (most recent call last):
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2302, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/klrshak/work/VisionLang/coarseLocal_env/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
